# GENERATED by ./generate-dockerfile from <role>/Dockerfile — do not edit.

ARG PHPVS
ARG NODEVS

FROM debian:bookworm-slim AS base
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=C.UTF-8
ENV TERM=linux
ENV TZ=UTC

ADD https://github.com/curatorium/steward/releases/download/v1.0.0-alpha.7/steward /usr/local/bin/steward
RUN chmod +x /usr/local/bin/steward

COPY base/files /

COPY base/Stewardfile /tmp/Stewardfile
RUN steward /tmp/Stewardfile && clean-tmp

ENTRYPOINT ["tini", "--", "entrypoint"]
HEALTHCHECK CMD ["healthcheck"]
STOPSIGNAL SIGTERM
WORKDIR /app

FROM base AS ci
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ARG NODEVS
ENV NODEVS=${NODEVS}
ENV ENABLED_SERVICES=""

COPY ci/files /

COPY ci/Stewardfile /tmp/Stewardfile
RUN steward /tmp/Stewardfile && clean-tmp

FROM ci AS az-ci
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ENV AZURE_CONFIG_DIR=/etc/azure/

COPY az-ci/files /

COPY az-ci/Stewardfile /tmp/Stewardfile
RUN steward /tmp/Stewardfile && clean-tmp

FROM base AS php-base
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ARG PHPVS
ENV PHPVS=${PHPVS}
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV NGINX_ENVSUBST_TEMPLATE_SUFFIX=.tpl
ENV ENABLED_SERVICES="php-fpm nginx"
ENV VAR_DUMPER_FORMAT=server

COPY php-base/files /
COPY --from=nginx:bookworm /docker-entrypoint.d/ /tmp/nginx-entrypoint/
COPY php-base/mods-available/ /etc/php/${PHPVS}/mods-available/

COPY php-base/Stewardfile /tmp/Stewardfile

RUN steward /tmp/Stewardfile && relocate-nginx-entrypoint && clean-tmp

EXPOSE 80 443 9000

FROM php-base AS php-qa
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ARG PHPVS
ENV PHPVS=${PHPVS}
ENV ENABLED_SERVICES=""

COPY php-qa/files /
COPY php-qa/mods-available/ /etc/php/${PHPVS}/mods-available/
COPY php-qa/Stewardfile /tmp/Stewardfile
RUN steward /tmp/Stewardfile && clean-tmp

FROM php-qa AS php-fs
LABEL org.opencontainers.image.authors="Curatorium"
LABEL org.opencontainers.image.vendor="Curatorium"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/curatorium/dockerfiles"
LABEL org.opencontainers.image.url="https://hub.docker.com/u/curatorium"

ARG NODEVS
ENV NODEVS=${NODEVS}
ENV ENABLED_SERVICES=""

COPY php-fs/Stewardfile /tmp/Stewardfile
RUN steward /tmp/Stewardfile && clean-tmp
