services:
  base:
    env_file: .env
    volumes: &volumes
      - ./files/entrypoint.d/00-override-owner.sh:/entrypoint.d/00-override-owner.sh
      - ./files/entrypoint.d/20-enable-newrelic-agent.sh:/entrypoint.d/20-enable-newrelic-agent.sh
      - ./files/etc/init.d/var-dump:/etc/init.d/var-dump
      - ./files/etc/nginx/templates:/etc/nginx/templates
      - ./files/usr/local/bin/add-az-cli:/usr/local/bin/add-az-cli
      - ./files/usr/local/bin/add-base:/usr/local/bin/add-base
      - ./files/usr/local/bin/add-ci:/usr/local/bin/add-ci
      - ./files/usr/local/bin/add-debug:/usr/local/bin/add-debug
      - ./files/usr/local/bin/add-docker:/usr/local/bin/add-docker
      - ./files/usr/local/bin/add-forensics:/usr/local/bin/add-forensics
      - ./files/usr/local/bin/add-node:/usr/local/bin/add-node
      - ./files/usr/local/bin/add-node-tools:/usr/local/bin/add-node-tools
      - ./files/usr/local/bin/add-nr-cli:/usr/local/bin/add-nr-cli
      - ./files/usr/local/bin/add-php:/usr/local/bin/add-php
      - ./files/usr/local/bin/add-qa:/usr/local/bin/add-qa
      - ./files/usr/local/bin/daemonize:/usr/local/bin/daemonize
      - ./files/usr/local/bin/clean-tmp:/usr/local/bin/clean-tmp
      - ./files/usr/local/bin/cloud-login:/usr/local/bin/cloud-login
      - ./files/usr/local/bin/entrypoint:/usr/local/bin/entrypoint
      - ./files/usr/local/bin/envsubst-only-prefix:/usr/local/bin/envsubst-only-prefix
      - ./files/usr/local/bin/service:/usr/local/bin/service
      - ./files/app:/app
      - ./tests:/tests

  ci:
    env_file: .env
    volumes: [/var/run/docker.sock:/var/run/docker.sock]

  qa:
    env_file: .env
    volumes: *volumes

  fs:
    env_file: .env
    volumes: *volumes
