services:
  base:
    build:
      args: &build-args {NODEVS: $NODEVS, PHPVS: $PHPVS}
      target: php-base
    image: curatorium/php-$PHPVS:base-$TS-$X_ARCH

  ci:
    build:
      args: *build-args
      target: ci
    depends_on: [base]
    image: curatorium/php-$PHPVS:ci-$TS-$X_ARCH

  qa:
    build:
      args: *build-args
      target: qa
    command: [bash]
    depends_on: [base]
    image: curatorium/php-$PHPVS:qa-$TS-$X_ARCH

  fs:
    build:
      args: *build-args
      target: fs
    command: [bash]
    depends_on: [qa]
    image: curatorium/php-$PHPVS:fs-$TS-$X_ARCH
