services:
  base:
    build:
      target: base
    image: curatorium/base:$TS-$X_ARCH

  ci:
    build:
      args: {NODEVS: $NODEVS}
      target: ci
    depends_on: [base]
    image: curatorium/ci:$TS-$X_ARCH

  az-ci:
    build:
      args: {NODEVS: $NODEVS}
      target: az-ci
    depends_on: [ci]
    image: curatorium/az-ci:$TS-$X_ARCH

  php-base:
    build:
      args: {PHPVS: $PHPVS}
      target: php-base
    depends_on: [base]
    image: curatorium/php-$PHPVS:base-$TS-$X_ARCH

  php-qa:
    build:
      args: {PHPVS: $PHPVS}
      target: php-qa
    command: [bash]
    depends_on: [php-base]
    image: curatorium/php-$PHPVS:qa-$TS-$X_ARCH

  php-fs:
    build:
      args: {NODEVS: $NODEVS, PHPVS: $PHPVS}
      target: php-fs
    command: [bash]
    depends_on: [php-qa]
    image: curatorium/php-$PHPVS:fs-$TS-$X_ARCH
