services:
  base:
    env_file: .env
    volumes:
      - ./base/files/entrypoint.d/00-override-owner.sh:/entrypoint.d/00-override-owner.sh
      - ./base/files/usr/local/bin/add-debug:/usr/local/bin/add-debug
      - ./base/files/usr/local/bin/add-forensics:/usr/local/bin/add-forensics
      - ./base/files/usr/local/bin/clean-tmp:/usr/local/bin/clean-tmp
      - ./base/files/usr/local/bin/daemonize:/usr/local/bin/daemonize
      - ./base/files/usr/local/bin/entrypoint:/usr/local/bin/entrypoint
      - ./base/files/usr/local/bin/envsubst-only-prefix:/usr/local/bin/envsubst-only-prefix
      - ./base/files/usr/local/bin/healthcheck:/usr/local/bin/healthcheck
      - ./base/files/usr/local/bin/service:/usr/local/bin/service
      - ./tests:/tests

  ci:
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ci/files/usr/local/bin/cloud-login:/usr/local/bin/cloud-login
      - ./tests:/tests

  az-ci:
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ci/files/usr/local/bin/cloud-login:/usr/local/bin/cloud-login
      - ./az-ci/files/usr/local/bin/cloud-login-az:/usr/local/bin/cloud-login-az
      - ./tests:/tests

  php-base:
    env_file: .env
    volumes: &php-volumes
      - ./base/files/entrypoint.d/00-override-owner.sh:/entrypoint.d/00-override-owner.sh
      - ./base/files/usr/local/bin/add-debug:/usr/local/bin/add-debug
      - ./base/files/usr/local/bin/add-forensics:/usr/local/bin/add-forensics
      - ./base/files/usr/local/bin/clean-tmp:/usr/local/bin/clean-tmp
      - ./base/files/usr/local/bin/daemonize:/usr/local/bin/daemonize
      - ./base/files/usr/local/bin/entrypoint:/usr/local/bin/entrypoint
      - ./base/files/usr/local/bin/envsubst-only-prefix:/usr/local/bin/envsubst-only-prefix
      - ./base/files/usr/local/bin/healthcheck:/usr/local/bin/healthcheck
      - ./base/files/usr/local/bin/service:/usr/local/bin/service
      - ./php-base/files/entrypoint.d/20-enable-newrelic-agent.sh:/entrypoint.d/20-enable-newrelic-agent.sh
      - ./php-base/files/etc/init.d/var-dump:/etc/init.d/var-dump
      - ./php-base/files/etc/nginx/templates:/etc/nginx/templates
      - ./php-base/files/app:/app
      - ./tests:/tests

  php-qa:
    env_file: .env
    volumes: *php-volumes

  php-fs:
    env_file: .env
    volumes: *php-volumes
