#!/bin/bash

ACTION="$1";
CMD="$(type -p var-dump-server)";
[[ -f "/app/vendor/bin/var-dump-server" ]] && CMD="/app/vendor/bin/var-dump-server";

service "$ACTION" var-dump "$CMD" --host=0.0.0.0:9912
