name: Build PHP 8.0
on:
  schedule: [{cron: '0 0 * * 1'}]
  workflow_dispatch: ~
jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions: {contents: read, id-token: write, attestations: write}
    with: {php: '8.0', node: '18'}
    secrets: inherit
